FROM caddy:builder AS builder

# Install the Cloudflare DNS module
RUN xcaddy build --with github.com/caddy-dns/cloudflare

FROM caddy:2.4.6-alpine

COPY --from=builder /usr/bin/caddy /usr/bin/caddy

COPY Caddyfile /etc/caddy/Caddyfile