version: '3.7'

services:
  mkdocs:
    image: ghcr.io/faraday-law/mkdocs:latest
    expose:
      - "8000"
    networks:
      - caddy_network

  caddy:
    image: ghcr.io/faraday-law/caddy:latest
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
    depends_on:
      - mkdocs
    networks:
      - caddy_network

networks:
  caddy_network:
    driver: bridge
