# Copyright (c) 2016-2024 Martin Donath <martin.donath@squidfunk.com>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

# Project information
site_name: Tzur Itzhak
site_url: https://tzuritzhak.com
site_author: Faraday
site_description: >-
  Welcome to the official website of Tzur Yitzhak City, your go-to source for 
  the latest updates and daily life in our vibrant community. Our content 
  is brought to you by independent authors dedicated to providing authentic 
  and insightful perspectives on local events, news, and activities.   

# Repository
repo_name: faraday-law/tzuritzhak.com
repo_url: https://github.com/faraday-law/tzuritzhak.com

# Copyright
copyright: Copyright &copy; 1987 - 2024 Faraday

# Configuration
theme:
  name: material
  language: en
  features:
    - navigation.footer
    - search.suggest
    - search.highlight
    - search.share
    - navigation.sections
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.indexes
  palette:
  - media: "(prefers-color-scheme)"
    toggle:
      icon: material/link
      name: Switch to light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: indigo
    accent: indigo
    toggle:
      icon: material/toggle-switch
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: black
    accent: indigo
    toggle:
      icon: material/toggle-switch-off
      name: Switch to system preference
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo

# Enable plugins
plugins:
  - rss:
      match_path: blog/posts/.* 
      date_from_meta:
        as_creation: date
      categories:
        - Yafe
        - Bullshit
        - Dogshit
  - blog:
      blog_toc: true
      blog_dir: . 
      authors_file: "{blog}/.authors.yml"
      categories_allowed:
        - Yafe
        - Bullshit
        - Dogshit
        - NoHate
  - search
  - tags

# Site Navigation
nav:
  - index.md

# Additional configuration
extra:
  status:
    new: Recently added
    deprecated: Deprecated
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/faraday-law/tzuritzhak.com

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true